services:
  eztools:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    image: quocdinhit97/eztools:latest
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - eztools-network

networks:
  eztools-network:
    driver: bridge
