services:
  eztools:
    image: quocdinhit97/eztools
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - eztools-network

networks:
  eztools-network:
    driver: bridge
